import cv2
import matplotlib.pyplot as plt

# Load images
img1 = cv2.imread(r"C:\Users\Ramya\OneDrive\Pictures\crime scene1.jpeg.")
img2 = cv2.imread(r"C:\Users\Ramya\OneDrive\Pictures\crime scene2.jpeg")
img3 = cv2.imread(r"C:\Users\Ramya\OneDrive\Pictures\Crimescene3.jpeg")
img4 = cv2.imread(r"C:\Users\Ramya\OneDrive\Pictures\crimescene4.jpeg")
img5 = cv2.imread(r"C:\Users\Ramya\OneDrive\Pictures\Crime scene5.jpeg")
img6 = cv2.imread(r"C:\Users\Ramya\OneDrive\Pictures\Crimescene6.jpeg")
# Convert BGR to RGB (important for display)
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2RGB)
img3 = cv2.cvtColor(img3, cv2.COLOR_BGR2RGB)
img4 = cv2.cvtColor(img4, cv2.COLOR_BGR2RGB)
img5 = cv2.cvtColor(img5, cv2.COLOR_BGR2RGB)
img6 = cv2.cvtColor(img6, cv2.COLOR_BGR2RGB)
# Display images
plt.imshow(img1)
plt.title("Image 1")
plt.axis('off')
plt.show()
plt.imshow(img2)
plt.title("Image 2")
plt.axis('off')
plt.show()
plt.imshow(img3)
plt.title("Image 3")
plt.axis('off')
plt.show()
plt.imshow(img4)
plt.title("Image 4")
plt.axis('off')
plt.show()
plt.imshow(img5)
plt.title("Image 5")
plt.axis('off')
plt.show()
plt.imshow(img6)
plt.title("Image 6")
plt.axis('off')
plt.show()
